name: Build Wheel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: centos/python-38-centos7

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install wheel

    - name: Download llama-cpp-python
      run: |
        pip download llama-cpp-python
        tar xzf llama_cpp_python*.tar.gz
        cd llama_cpp_python*
        ls

    - name: Build wheel
      run: python setup.py bdist_wheel

    - name: Save wheel files
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist/*.whl
