name: Build wheel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build . -t my-python-package -f Dockerfile

    - name: Run Docker container
      run: |
        docker run --name my-container my-python-package

    - name: Copy wheel file from Docker container
      run: |
        docker cp my-container:/src/dist ./dist

    - name: Upload wheel file
      uses: actions/upload-artifact@v2
      with:
        name: wheel-file
        path: dist/*.whl
